name: deepIoM-tf1
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow-gpu==1.15.0
    - opencv-python==4.1.1.26
    - bcolz==1.2.1
    - sklearn2
    - PyYAML
    - tqdm
