# general
samples_per_class: 4
classes_per_batch: 32
batch_size: 128
input_size: 112
# embd_shape is for the Resnet, backbone
embd_shape: 512
#iom_res50_twostage_triplet -- only two stage with triplet loss
#iom_res50_twostage_triplet and quantization loss -- triplet loss + quantization loss, this in another config file
sub_name: 'iom_res50_twostage_arctriplet_online'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: IoMHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train /media/xingbo/Storage/facedata/vgg_mtcnnpy_160 ./data/split
train_dataset: '/media/xingbo/Storage/facedata/vgg_mtcnnpy_160'
binary_img: False
num_classes: 85742
# I generate 1 milion triplets
num_samples: 1000000
epochs: 5
base_lr: 0.001
w_decay: !!float 5e-4
save_steps: 5000
q: 8
# m, the projection length would be m x q
m: 256
# test
test_dataset: './data/test_dataset'
