# general
batch_size: 200
input_size: 112
# embd_shape is for the Resnet, backbone
embd_shape: 512
sub_name: 'iom_res50_triplet'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: IoMHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/triplets_ds.tfrecord'
# triplet loss not binary
binary_img: False
num_classes: 85742
# I generate 1 milion triplets
num_samples: 3000000
epochs: 10
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 10000
q: 8
# m, the projection length would be m x q
m: 256
# test
test_dataset: './data/test_dataset'
